import { parse } from 'csv-parse/sync';
import ExcelJS from 'exceljs';
import { normalize } from './core.mjs';
export const aliases={text:['text','content','comment','评论','评论内容','评论正文','正文','内容'],platform:['platform','平台','来源平台'],comment_id:['comment_id','cid','评论id','评论ID','id'],post_id:['post_id','aweme_id','note_id','作品id','作品ID','笔记ID','视频ID'],source_url:['source_url','url','link','来源链接','作品链接','链接','笔记链接','视频链接'],title:['title','标题','作品标题','笔记标题'],created_at:['created_at','create_time','time','时间','评论时间','发布时间'],likes:['likes','digg_count','like_count','点赞数','点赞'],parent_id:['parent_id','reply_id','父评论ID','父评论id'],author:['author','nickname','用户名','作者','昵称']};
export function mappingFor(headers) { return Object.fromEntries(Object.entries(aliases).map(([key,values])=>[key,headers.find(h=>values.some(v=>v.toLowerCase()===h.toLowerCase().trim()))||''])); }
export async function readRows(buffer,filename){const ext=filename.split('.').pop().toLowerCase();let rows;
 if(ext==='csv'||ext==='tsv') {let s=new TextDecoder('utf-8',{fatal:true}).decode(buffer);rows=parse(s,{columns:headers=>{const clean=headers.map(h=>h.trim());if(clean.some(h=>!h)||new Set(clean).size!==clean.length)throw new Error('表头不能为空或重名，请修改后重新导入');return clean;},bom:true,skip_empty_lines:true,delimiter:ext==='tsv'?'\t':',',max_record_size:100000});}
 else if(ext==='json'){const data=JSON.parse(buffer.toString('utf8'));rows=Array.isArray(data)?data:data.comments||data.data?.comments||data.data||data.rows;}
 else if(ext==='xlsx'){const wb=new ExcelJS.Workbook();await wb.xlsx.load(buffer);const ws=wb.worksheets[0];if(!ws)throw new Error('表格没有工作表');const cell=v=>v instanceof Date?v.toISOString():v?.richText?v.richText.map(x=>x.text).join(''):v?.text??v?.result??v??'';const headers=ws.getRow(1).values.slice(1).map(v=>String(cell(v)));if(new Set(headers).size!==headers.length)throw new Error('表头不能重名');rows=[];ws.eachRow((row,n)=>{if(n>1)rows.push(Object.fromEntries(headers.map((h,i)=>[h,cell(row.getCell(i+1).value)])));});}
 else throw new Error('支持 CSV、TSV、XLSX 和 JSON；CSV 请使用 UTF-8 编码');
 if(!Array.isArray(rows)||!rows.length)throw new Error('文件中没有评论记录');if(rows.length>50000)throw new Error('单次最多导入 50,000 条，请拆分文件');if(rows.some(r=>!r||typeof r!=='object'||Array.isArray(r)))throw new Error('每条评论必须是有字段的记录');const headers=[...new Set(rows.flatMap(r=>Object.keys(r)))];if(headers.length>100)throw new Error('字段超过 100 列，请只保留评论相关列');return {rows,headers,mapping:mappingFor(headers)};}
export function mapRows(rows,mapping,defaults={}){if(!mapping.text)throw new Error('请选择评论正文字段');return rows.map(r=>normalize(Object.fromEntries(Object.keys(aliases).map(k=>[k,r[mapping[k]]??''])),defaults)).filter(Boolean);}
export function csv(rows,columns){const esc=v=>{let s=String(v??'');if(/^[\s]*[=+\-@]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';};return '\uFEFF'+[columns.map(c=>esc(c[1])).join(','),...rows.map(r=>columns.map(c=>esc(r[c[0]])).join(','))].join('\r\n');}
