import path from 'node:path';
import {existsSync} from 'node:fs';
import {spawn} from 'node:child_process';
import {normalize,sourceUrl,sourceId,safeUrl} from './core.mjs';
import {PLATFORM_INFO,PLATFORM_NAMES} from '../public/platforms.js';

export function postIdentity(row){return String(row.note_id||row.aweme_id||row.video_id||row.content_id||'');}
export function postUrl(p,id,row={}){const supplied=row.note_url||row.video_url||row.content_url;if(supplied){try{const v=sourceUrl(supplied);if(v.platform===p)return v.url;}catch{}}
 const encoded=encodeURIComponent(id);return ({douyin:`https://www.douyin.com/video/${encoded}`,xiaohongshu:`https://www.xiaohongshu.com/explore/${encoded}`,kuaishou:`https://www.kuaishou.com/short-video/${encoded}`,bilibili:`https://www.bilibili.com/video/av${encoded}`,weibo:`https://m.weibo.cn/detail/${encoded}`,tieba:`https://tieba.baidu.com/p/${encoded}`,zhihu:row.content_type==='article'?`https://zhuanlan.zhihu.com/p/${encoded}`:`https://www.zhihu.com/${row.content_type==='zvideo'?'zvideo/':'answer/'}${encoded}`})[p]||'';}
export function mapMCComment(p,row,post={}){return normalize({platform:p,post_id:postIdentity(row),comment_id:row.comment_id,text:row.content,created_at:row.create_time||row.publish_time,likes:row.like_count??row.comment_like_count,parent_id:String(row.parent_comment_id||'')==='0'?'':row.parent_comment_id,author:row.nickname||row.user_nickname,source_url:postUrl(p,postIdentity(row),{...row,...post}),title:post.title||post.desc||''});}
export function mcInput(p,link,mode){const u=new URL(link);if(p==='weibo')return u.pathname.split('/').filter(Boolean).at(-1);if(p==='tieba'&&mode==='links')return sourceId(link);return link;}
export class MediaCollector {
 constructor(store,root,connections,{spawnImpl=spawn,stateFor}={}){this.store=store;this.root=root;this.connections=connections;this.spawn=spawnImpl;this.stateFor=stateFor;this.active=null;this.job=null;this.child=null;this.stop=false;this.python=path.join(root,'.runtime/vendor/MediaCrawler/.venv/bin/python');this.script=path.join(root,'src/bridge/mediacrawler.py');}
 status(){const ready=existsSync(this.python)&&existsSync(path.join(this.root,'.runtime/vendor/MediaCrawler/.workbench-ready.json'));return {ready,name:'MediaCrawler',platforms:PLATFORM_INFO.map(p=>p.id),license:'非商业学习使用许可证 1.1',message:ready?'增强采集已安装；可使用关键词、作品链接或创作者主页':'增强采集尚未安装或未通过运行检查'};}
 async run(id){if(this.active)throw Error('已有增强采集任务在运行');if(!this.status().ready)throw Error('MediaCrawler 尚未安装完成，请完成运行环境检查');const task=this.store.get(id);this.active=id;this.stop=false;this.store.update(id,{status:'running',message:'正在启动增强采集…'});this.job=this.execute(task).catch(()=>{this.store.update(id,{status:this.stop?'paused':'blocked',message:'增强采集未完成，已保存数据；请检查登录和运行环境后继续'});}).finally(()=>{this.active=null;this.stop=false;this.job=null;});return this.store.get(id);}
 pause(id){if(this.active!==id)throw Error('该任务当前没有在采集');this.stop=true;this.store.update(id,{status:'stopping',message:'正在停止增强采集，已读取评论正在保存'});if(this.child){const child=this.child;child.kill('SIGTERM');const timer=setTimeout(()=>{if(this.child===child)child.kill('SIGKILL');},8000);timer.unref();}}
 async execute(task){const platforms=task.mode==='search'?task.options.platforms:[...new Set((task.options.links||[]).map(l=>l.platform))];let failures=0,done=false;const reasons=[];
 for(const p of platforms){if(this.stop)break;const links=(task.options.links||[]).filter(l=>l.platform===p).map(l=>mcInput(p,l.url,task.mode));const spec={platform:p,mode:task.mode,links:task.mode==='links'?links:[],creators:task.mode==='creator'?links:[],query:task.options.query||'',maxPosts:task.options.maxPosts,maxComments:task.options.maxComments,includeReplies:task.options.includeReplies!==false,interval:3};if(this.stateFor){spec.storageState=await this.stateFor(p);spec.taskId=task.id;}if(this.stop)break;const outcome=await this.process(task,p,spec);if(outcome.error){failures++;reasons.push(PLATFORM_NAMES[p]+'：'+(outcome.reason||'未正常完成'));}done||=outcome.done;}
 for(const s of this.store.sources(task.id)){if(s.status==='running')this.store.source(task.id,s.id,s.url,s.platform,s.count>=(task.options.maxComments??Infinity)?'limit':'partial',this.stop?'已暂停，已读评论保留':'已读取当前样本，未确认评论全量',s.count);}
 const count=this.store.get(task.id).count;this.store.update(task.id,{status:this.stop?'paused':count?'partial':failures||!done?'blocked':'completed',message:this.stop?'已暂停；继续时重新读取并去重，已保存评论不会丢失':count?`增强采集结束，共 ${count} 条去重评论，仅代表已获取样本。${failures?'部分平台未完成，可处理登录或验证后继续。':''}`:failures?reasons.join('；'):'本次流程结束，未返回评论。请核对来源页面或调整搜索条件。'});}
 process(task,p,spec){return new Promise(resolve=>{let outcome={done:false,error:false},buffer='';const posts=new Map();const existing=this.store.comments(task.id).filter(c=>c.platform===p);const keys=new Set(existing.map(c=>c.key));const counts=new Map();for(const c of existing)counts.set(c.post_id,(counts.get(c.post_id)||0)+1);
 const onEvent=e=>{if(e.event==='post'){const id=postIdentity(e.data);if(!id)return;const sid=p+':'+id;const sources=this.store.sources(task.id);if(!sources.some(s=>s.id===sid)&&sources.length>=task.options.maxPosts)return;posts.set(id,e.data);this.store.source(task.id,sid,postUrl(p,id,e.data),p,'running','正在读取评论',counts.get(id)||0);}
 else if(e.event==='comment'){const c=mapMCComment(p,e.data,posts.get(postIdentity(e.data)));if(!c)return;if(keys.has(c.key)||(counts.get(c.post_id)||0)>=(task.options.maxComments??Infinity)){this.store.recordReads(task.id,1);return;}const sid=p+':'+c.post_id;const sources=this.store.sources(task.id);if(!sources.some(s=>s.id===sid)&&sources.length>=task.options.maxPosts)return;this.store.insert(task.id,[c]);keys.add(c.key);counts.set(c.post_id,(counts.get(c.post_id)||0)+1);this.store.source(task.id,sid,c.source_url,p,'running','评论已保存，正在继续读取',counts.get(c.post_id));this.connections[p]={state:'verified',message:'增强采集已读取评论'};}
 else if(['status','attention','warning','error'].includes(e.event)){const message=String(e.message||'采集未完成').slice(0,200);if(!this.stop)this.store.update(task.id,{message:PLATFORM_NAMES[p]+'：'+message});if(['error','warning'].includes(e.event)){outcome.error=true;outcome.reason=message+(e.code?'（'+String(e.code).replace(/[^a-zA-Z0-9_]/g,'')+'）':'');}if(['attention','error','warning'].includes(e.event))this.connections[p]={state:'attention',message};}
 else if(e.event==='done'){outcome.done=true;outcome.error||=!!e.partial;}};
 const child=this.spawn(this.python,[this.script],{cwd:this.root,env:{...process.env,PYTHONUNBUFFERED:'1',PYTHONIOENCODING:'utf-8'},stdio:['pipe','pipe','pipe']});this.child=child;
 child.stdout.setEncoding('utf8');child.stdout.on('data',chunk=>{buffer+=chunk;if(buffer.length>2e6){outcome.error=true;child.kill('SIGTERM');buffer='';return;}let newline;while((newline=buffer.indexOf('\n'))>=0){const line=buffer.slice(0,newline);buffer=buffer.slice(newline+1);try{onEvent(JSON.parse(line));}catch{outcome.error=true;}}});
 child.stderr.resume();child.stdin.on('error',()=>{});child.stdin.end(JSON.stringify(spec));child.on('error',()=>{outcome.error=true;});child.on('close',code=>{if(this.child===child)this.child=null;outcome.error||=code!==0&&!this.stop;resolve(outcome);});
 });}
 async close(){if(this.active)this.pause(this.active);await this.job;}
}
