import test from 'node:test';import http from 'node:http';import assert from 'node:assert/strict';import {mkdtemp,rm}from'node:fs/promises';import os from'node:os';import path from'node:path';import{createApp}from'../src/server.mjs';
const fake=store=>({active:null,connectionState:{},close:async()=>{},connect:async()=>({state:'opened'}),pause(id){store.update(id,{status:'paused'});this.active=null;},async run(id){if(this.active)throw new Error('busy');this.active=id;store.update(id,{status:'running'});}});
async function start(dbPath){const app=await createApp({dbPath,collectorFactory:fake});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+app.server.address().port;const req=async(route,data)=>{const res=await fetch(base+route,data===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});return{status:res.status,body:await res.json()}};return{app,base,req};}
test('API 导入、重复提交、追加去重、筛选收藏、导出、重启恢复完整闭环',async()=>{const dir=await mkdtemp(path.join(os.tmpdir(),'comment-test-'));let s;try{s=await start(path.join(dir,'db.sqlite'));const data=Buffer.from('评论ID,作品ID,评论内容,平台,来源链接\n1,v1,价格太贵了,抖音,https://www.douyin.com/video/1\n2,v1,如何学习剪辑,抖音,https://www.douyin.com/video/1').toString('base64');let p=(await s.req('/api/import/preview',{filename:'comments.csv',data})).body;const b={token:p.token,mapping:p.mapping};const r=await s.req('/api/import/commit',b);assert.equal(r.status,200);const id=r.body.task.id;assert.equal((await s.req('/api/import/commit',b)).body.task.id,id);p=(await s.req('/api/import/preview',{filename:'comments.csv',data})).body;const append=await s.req('/api/import/commit',{...b,token:p.token,taskId:id});assert.equal(append.body.duplicates,2);let detail=(await s.req(`/api/tasks/${id}`)).body;assert.equal(detail.analysis.total,2);assert.equal(detail.comments.length,2);await s.req(`/api/tasks/${id}/favorite`,{key:detail.comments[0].key,on:true});assert.equal((await s.req(`/api/tasks/${id}?favorite=1`)).body.matched,1);assert.equal((await s.req(`/api/tasks/${id}?q=价格`)).body.matched,1);let exportRes=await fetch(s.base+`/api/tasks/${id}/export?format=xlsx`);assert.equal(exportRes.status,200);assert.ok((await exportRes.arrayBuffer()).byteLength>500);exportRes=await fetch(s.base+`/api/tasks/${id}/export?format=csv&q=价格`);const exported=await exportRes.text();assert.ok(exported.includes('价格太贵了'));assert.ok(!exported.includes('如何学习剪辑'));
const live=(await s.req('/api/tasks',{mode:'links',input:'https://www.douyin.com/video/123'})).body.task;assert.equal(live.status,'running');await s.app.close();s=await start(path.join(dir,'db.sqlite'));assert.equal((await s.req(`/api/tasks/${live.id}`)).body.task.status,'paused');detail=(await s.req(`/api/tasks/${id}`)).body;assert.equal(detail.comments[0].favorite,true);assert.equal(detail.analysis.total,2);
}finally{if(s)await s.app.close();await rm(dir,{recursive:true,force:true});}});
test('HTTP 拒绝跨站写入、伪造 Host、错误链接，未找到路由返回404',async()=>{const s=await start(':memory:');try{assert.equal((await fetch(s.base+'/api/demo',{method:'POST',headers:{Origin:'https://evil.example','Content-Type':'application/json'},body:'{}'})).status,403);assert.equal(await new Promise((resolve,reject)=>{http.get(s.base+'/api/state',{headers:{Host:'evil.example'}},r=>{r.resume();resolve(r.statusCode);}).on('error',reject);}),403);assert.equal((await s.req('/api/tasks',{mode:'links',input:'https://127.0.0.1/secret'})).status,400);assert.equal((await s.req('/api/tasks/unknown')).status,404);assert.equal((await s.req('/api/no-such-route')).status,404);}finally{await s.app.close();}});

test('分页越界归位、关键词导出遵循筛选、不接受不存在日期',async()=>{const s=await start(':memory:');try{const demo=(await s.req('/api/demo',{})).body.task;const result=(await s.req(`/api/tasks/${demo.id}?page=999`)).body;assert.equal(result.page,result.pages);assert.ok(result.comments.length>0);const exported=await(await fetch(s.base+`/api/tasks/${demo.id}/export?kind=keywords&format=csv&q=不可能匹配的词xyz`)).text();assert.equal(exported.trim().split('\r\n').length,1);const invalid=await s.req('/api/tasks',{mode:'links',input:'https://www.douyin.com/video/123',options:{since:'2026-02-30'}});assert.equal(invalid.status,400);assert.match(invalid.body.error,/日期/);}finally{await s.app.close();}});

test('新增JSON与词云导出沿用筛选，页面方式拒绝未支持的平台',async()=>{const s=await start(':memory:');try{const t=(await s.req('/api/demo',{})).body.task;const d=await(await fetch(s.base+`/api/tasks/${t.id}/export?format=json&q=价格`)).json();assert.ok(d.comments.length);assert.ok(d.comments.every(c=>c.text.includes('价格')));const svg=await fetch(s.base+`/api/tasks/${t.id}/export?kind=wordcloud`);assert.equal(svg.headers.get('content-type'),'image/svg+xml; charset=utf-8');assert.ok((await svg.text()).includes('<svg'));const bad=await s.req('/api/tasks',{mode:'links',engine:'browser',input:'https://www.bilibili.com/video/BV123'});assert.equal(bad.status,400);assert.match(bad.body.error,/增强采集/);}finally{await s.app.close();}});
