import test from 'node:test';import assert from 'node:assert/strict';
import {normalize,sourceUrl,analyze,eligible,classify,sentiment,number} from '../src/lib/core.mjs';
import {readRows,mapRows,csv} from '../src/lib/import.mjs';
import {Store} from '../src/lib/store.mjs';
import {decodeComments,decodeDiscovery} from '../src/lib/collector.mjs';
import ExcelJS from 'exceljs';
const row=(text,extra={})=>normalize({text,platform:'douyin',post_id:'p1',...extra});
test('合法分享文本识别；拒绝外部、伪造域名与私有地址',()=>{assert.equal(sourceUrl('复制链接 https://v.douyin.com/abc/ 看视频').platform,'douyin');for(const u of ['http://127.0.0.1/x','https://douyin.com.attacker.test/video/1','https://a@www.douyin.com/video/1','https://www.douyin.com:4433/'])assert.throws(()=>sourceUrl(u));assert.equal(sourceUrl('https://www.xiaohongshu.com/explore/abc?xsec_token=test').platform,'xiaohongshu');});
test('平台 ID 去重，不合并不同作者的同文评论；任务快照互不改变',()=>{const db=new Store(':memory:');const a=db.create({name:'a',mode:'import'}),b=db.create({name:'b',mode:'import'});const first=row('好用',{comment_id:'1',likes:1});assert.deepEqual(db.insert(a.id,[first,first]),{added:1,duplicates:1});db.insert(b.id,[{...first,likes:10}]);assert.equal(db.comments(a.id)[0].likes,1);assert.equal(db.comments(b.id)[0].likes,10);assert.notEqual(row('好用',{author:'甲'}).key,row('好用',{author:'乙'}).key);db.close();});
test('词频、评论数、作品数口径不同；原文证据不丢失',()=>{const a=analyze([row('价格价格太贵',{comment_id:'1'}),row('价钱能便宜吗',{comment_id:'2'}),row('费用是否免费',{post_id:'p2',comment_id:'3'})]);const k=a.keywords.find(k=>k.word==='价格');assert.ok(k);assert.equal(k.comments,3);assert.equal(k.posts,2);assert.equal(k.occurrences,4);assert.equal(k.ids.length,3);});
test('否定语境不误标困难；购买咨询可与其他类别并存',()=>{assert.equal(sentiment('价格不贵，没有报错'),'正面');assert.ok(!classify('价格不贵，不会报错').includes('遇到困难'));assert.ok(classify('价格太贵了，如何申请试用').includes('遇到困难'));});
test('日期以北京时间过滤，未知日期不混入指定范围',()=>{assert.equal(eligible(row('有效评论',{created_at:'2026-10-03T16:30:00Z'}),{since:'2026-10-04'}),true);assert.equal(eligible(row('有效评论',{created_at:'2026-10-03T15:59:00Z'}),{since:'2026-10-04'}),false);assert.equal(eligible(row('无时间'),{since:'2026-10-04'}),false);assert.equal(eligible(row('有效评论',{created_at:'2026-10-04T16:00:00Z'}),{until:'2026-10-04'}),false);});
test('推广、无效文本过滤可恢复；关注词不自动缩小样本',()=>{const a=analyze([row('哈哈哈😂'),row('加我领取兼职返利'),row('产品价格多少钱')],{watch:'价格'});assert.equal(a.valid,1);assert.equal(a.noise,2);assert.equal(analyze([row('哈哈哈😂')],{includeNoise:true}).valid,1);assert.equal(a.watch[0].count,1);});
test('CSV 包含换行引号、中文列名，保留来源；非 UTF-8 给出错误',async()=>{const p=await readRows(Buffer.from('评论内容,平台,来源链接\r\n"如何剪辑\n字幕？",小红书,https://www.xiaohongshu.com/explore/abc'),'a.csv');assert.equal(p.rows.length,1);const rows=mapRows(p.rows,p.mapping);assert.equal(rows[0].platform,'xiaohongshu');assert.equal(rows[0].text,'如何剪辑 字幕?');assert.ok(rows[0].source_url);assert.throws(()=>mapRows(p.rows,{text:''}));await assert.rejects(()=>readRows(Buffer.from([0xff,0xff]),'a.csv'));});
test('XLSX 日期与公式计算结果可以导入，JSON 结构错误应拒绝',async()=>{const wb=new ExcelJS.Workbook(),ws=wb.addWorksheet('评论');ws.addRow(['评论内容','评论时间','点赞数']);ws.addRow(['价格怎么样',new Date('2026-10-04T01:00:00Z'),{formula:'1+2',result:3}]);const p=await readRows(Buffer.from(await wb.xlsx.writeBuffer()),'test.xlsx');const r=mapRows(p.rows,p.mapping)[0];assert.equal(r.likes,3);assert.equal(r.created_at,'2026-10-04T01:00:00.000Z');await assert.rejects(()=>readRows(Buffer.from('{"a":1}'),'x.json'));});
test('CSV 防止表格公式注入，转义引号与逗号',()=>{const s=csv([{text:'=HYPERLINK("evil")'},{text:'a,b'}],[['text','正文']]);assert.ok(s.includes("'=HYPERLINK"));assert.ok(s.includes('"a,b"'));});
test('抖音响应解析与父子关系',()=>{const r=decodeComments({comments:[{cid:'1',text:'怎么用',create_time:1728000000,digg_count:12,reply_comment:[{cid:'2',text:'先安装'}]}]},'douyin',{post_id:'p1',source_url:'https://www.douyin.com/video/1'});assert.equal(r.length,2);assert.equal(r[1].parent_id,'1');assert.equal(r[0].likes,12);});
test('小红书一级及子评论解析，未知响应不造数据',()=>{const r=decodeComments({data:{comments:[{id:'1',content:'求教程',like_count:'1.2万',create_time:1728000000000,sub_comments:[{id:'2',content:'已经发布'}]}]}},'xiaohongshu',{post_id:'abc'});assert.equal(r.length,2);assert.equal(r[1].parent_id,'1');assert.equal(r[0].likes,12000);assert.deepEqual(decodeComments({data:{items:[{title:'非评论'}]}},'douyin',{}),[]);});
test('计数支持千、万；异常数值不会污染统计',()=>{assert.equal(number('1.2万'),12000);assert.equal(number('点赞'),0);assert.equal(number(-10),0);});

test('平台正常搜索响应可发现作品，广告与非笔记项不误采',()=>{assert.deepEqual(decodeDiscovery({data:[{aweme_info:{aweme_id:'12345678'}},{user_info:{uid:'xx'}}]},'douyin'),['https://www.douyin.com/video/12345678']);const x=decodeDiscovery({data:{items:[{model_type:'note',id:'68aabbccddeeff0011223344',xsec_token:'test-token'},{model_type:'user',id:'68aabbccddeeff0011223345'}]}},'xiaohongshu');assert.equal(x.length,1);assert.equal(new URL(x[0]).searchParams.get('xsec_source'),'pc_search');});

test('领域词保留完整含义，弱信息词不进入关键词榜',()=>{const a=analyze([row('我也做了小程序，需要企业资质'),row('小程序的企业资质怎么办')]);assert.equal(a.keywords.find(k=>k.word==='小程序').comments,2);assert.equal(a.keywords.find(k=>k.word==='企业资质').comments,2);assert.equal(a.keywords.some(k=>['我也','做了'].includes(k.word)),false);assert.ok(classify('发布需要企业资质').includes('场景需求'));});

test('导入拒绝重名或空表头，防止覆盖原始列',async()=>{for(const header of ['评论内容,评论内容','评论内容, 评论内容 ','评论内容,'])await assert.rejects(()=>readRows(Buffer.from(header+'\n甲,乙'),'x.csv'),/表头/);});
test('未带时区的导入日期按北京时间解释',()=>{assert.equal(row('时间测试',{created_at:'2026-10-04'}).created_at,'2026-10-03T16:00:00.000Z');assert.equal(row('时间测试',{created_at:'2026/10/4 10:30:00'}).created_at,'2026-10-04T02:30:00.000Z');});
test('独立回复分页保留父评论，内嵌回复不被默认父级覆盖',()=>{const r=decodeComments({data:{comments:[{id:'2',content:'回复正文',sub_comments:[{id:'3',content:'继续回复'}]}]}},'xiaohongshu',{post_id:'abc',parent_id:'1'});assert.equal(r[0].parent_id,'1');assert.equal(r[1].parent_id,'2');});
