import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,stat,readFile} from 'node:fs/promises';
import os from 'node:os';import path from 'node:path';
import {Store} from '../src/lib/store.mjs';
import {Feishu,parseBase} from '../src/lib/feishu.mjs';
import {createApp} from '../src/server.mjs';
import {mockFeishu} from './helpers/feishu.mjs';
const rows=n=>Array.from({length:n},(_,i)=>({key:'comment-'+i,text:'评论正文'+i,platform:'xiaohongshu',likes:i,comment_id:String(i),favorite:false}));
async function fixture(){const dir=await mkdtemp(path.join(os.tmpdir(),'feishu-test-')),store=new Store(':memory:'),mock=mockFeishu(),file=path.join(dir,'feishu.json');return {dir,store,mock,file,f:new Feishu(store,file,mock),close:async()=>{store.close();await rm(dir,{recursive:true,force:true});}};}
const config={appId:'cli_test',appSecret:'test-secret',baseUrl:'https://sample.feishu.cn/base/baseTest?table=tblOld'};
test('飞书链接限制域名和类型，表格ID不混入Base地址',()=>{assert.deepEqual(parseBase(config.baseUrl),{token:'baseTest',url:'https://sample.feishu.cn/base/baseTest'});for(const url of ['https://feishu.cn.evil.test/base/x','http://sample.feishu.cn/base/x','https://sample.feishu.cn/wiki/x','https://user:pass@sample.feishu.cn/base/x','https://127.0.0.1/base/x'])assert.throws(()=>parseBase(url));});
test('配置仅本机保存且不回传密钥，空密钥沿用，换应用须重填',async()=>{const x=await fixture();try{const status=await x.f.save(config);assert.equal(status.hasSecret,true);assert.ok(!JSON.stringify(status).includes(config.appSecret));assert.equal((await stat(x.file)).mode&0o777,0o600);await x.f.save({...config,appSecret:''});assert.equal(JSON.parse(await readFile(x.file,'utf8')).appSecret,config.appSecret);await assert.rejects(()=>x.f.save({...config,appId:'cli_other',appSecret:''}),/App Secret/);}finally{await x.close();}});
test('分批导出、重复点击不增行，丢失成功响应后可恢复且不重复',async()=>{const x=await fixture();try{await x.f.save(config);x.mock.state.failAfterWrite=true;await assert.rejects(()=>x.f.export({id:'task1',name:'评论测试'},rows(405)),/网络异常/);assert.equal(x.mock.state.records.length,200);const restarted=new Feishu(x.store,x.file,x.mock);const r=await restarted.export({id:'task1',name:'评论测试'},rows(405));assert.equal(r.total,405);assert.equal(r.added,205);assert.equal(x.mock.state.tables.length,1);assert.equal(x.mock.state.records.length,405);assert.deepEqual(x.mock.state.batches,[200,200,5]);const again=await restarted.export({id:'task1',name:'评论测试'},rows(405));assert.equal(again.added,0);assert.equal(again.skipped,405);}finally{await x.close();}});
test('权限错误提供处理路径，不把远端错误正文或密钥返回页面',async()=>{const x=await fixture();try{x.mock.state.failCode=1254302;await assert.rejects(()=>x.f.save(config),e=>/协作者/.test(e.message)&&!e.message.includes('credential'));assert.equal((await x.f.status()).configured,false);}finally{await x.close();}});
test('飞书导出API沿用评论筛选且空筛选不会写表',async()=>{const dir=await mkdtemp(path.join(os.tmpdir(),'feishu-api-'));const mock=mockFeishu();const app=await createApp({dbPath:':memory:',feishuConfigPath:path.join(dir,'config.json'),feishuOptions:mock});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+app.server.address().port;const post=async(route,data)=>{const r=await fetch(base+route,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});return {status:r.status,data:await r.json()};};try{const demo=(await post('/api/demo',{})).data.task;const missing=await post('/api/tasks/'+demo.id+'/feishu',{});assert.equal(missing.status,400);await post('/api/feishu',config);const expected=await(await fetch(base+'/api/tasks/'+demo.id+'?q=价格')).json();const result=await post('/api/tasks/'+demo.id+'/feishu?q=价格',{});assert.equal(result.status,200);assert.equal(result.data.total,expected.matched);assert.ok(mock.state.records.every(r=>r.fields['评论内容'].includes('价格')));const empty=await post('/api/tasks/'+demo.id+'/feishu?q=无匹配xyz',{});assert.equal(empty.status,400);assert.equal(mock.state.tables.length,1);}finally{await app.close();await rm(dir,{recursive:true,force:true});}});
