import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,writeFile,rm} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {Readable} from 'node:stream';import {VideoWorkbench,videoLink} from '../src/lib/video-workbench.mjs';
const wait=async fn=>{for(let i=0;i<100;i++){if(fn())return;await new Promise(r=>setTimeout(r,10));}throw Error('timeout');};
test('Video links restrict protocols, credentials, private hosts and fake domains',()=>{assert.equal(videoLink('分享 https://www.douyin.com/video/12345'),'https://www.douyin.com/video/12345');for(const u of ['http://youtube.com/x','https://127.0.0.1/x','https://youtube.com.evil.test/x','https://user:pass@youtube.com/x','https://youtube.com:444/x'])assert.throws(()=>videoLink(u));});
test('Local uploads, queued processing, independent results and archive retain files',async()=>{const dir=await mkdtemp(path.join(os.tmpdir(),'video-test-'));let active=0,max=0;const v=new VideoWorkbench(process.cwd(),{directory:dir,runner:async(item,folder)=>{active++;max=Math.max(max,active);await new Promise(r=>setTimeout(r,15));await writeFile(path.join(folder,'result.json'),JSON.stringify({text:item.spec.text,files:[]}));active--;}});try{await v.ready;await assert.rejects(()=>v.upload(Readable.from(['abc']),'bad.html'),/支持/);const upload=await v.upload(Readable.from(['abc']),'../audio.wav');assert.equal(upload.item.title,'audio.wav');assert.equal(upload.item.status,'ready');const a=await v.create({kind:'summary',text:'素材A'}),b=await v.create({kind:'hooks',text:'素材B'});await wait(()=>v.get(b.item.id).status==='completed');assert.equal(max,1);assert.equal(v.get(a.item.id).text,'素材A');assert.equal(v.get(b.item.id).text,'素材B');await v.action(a.item.id,'archive');assert.ok(!v.list().some(i=>i.id===a.item.id));assert.equal(v.get(a.item.id).text,'素材A');await assert.rejects(()=>v.create({kind:'summary',sourceId:'missing'}),/不存在/);await assert.rejects(()=>v.create({kind:'clone',text:'hello'}),/参考音频/);}finally{await v.close();await rm(dir,{recursive:true,force:true});}});

test('Browser media is bound to the requested post, excludes login/recommendation videos',async()=>{const {matchingMedia}=await import('../src/lib/video-browser.mjs');const data={aweme_list:[{aweme_id:'other',video:{play_addr:{url_list:['https://cdn.example/other.mp4']}}},{aweme_id:'target',desc:'correct',video:{play_addr:{url_list:['https://cdn.example/right.mp4']}}}]};assert.deepEqual(matchingMedia(data,'target'),[{urls:['https://cdn.example/right.mp4'],title:'correct'}]);assert.deepEqual(matchingMedia({video:{play_addr:{url_list:['https://cdn.example/login.mp4']}}},'target'),[]);});

 test('All tools accept source URLs, URL overrides stale material and failed processing retains extraction',async()=>{
 const dir=await mkdtemp(path.join(os.tmpdir(),'video-source-test-'));const v=new VideoWorkbench(process.cwd(),{directory:dir,runner:async(item,folder)=>{await writeFile(path.join(folder,'media.mp4'),'fixture');await writeFile(path.join(folder,'result.json'),JSON.stringify({text:'source title',files:['media.mp4','../private']}));throw Error('downstream failed');}});
 try{await v.ready;for(const kind of ['download','transcribe','subtitles','ocr','summary','hooks','script','translate','chat','tts','clone','cover']){const {item}=await v.create({kind,url:'https://www.douyin.com/video/12345',sourceId:'stale'});assert.equal(item.spec.sourceText,undefined);await wait(()=>v.get(item.id).status==='failed');assert.deepEqual(v.get(item.id).files,['media.mp4']);assert.equal(v.get(item.id).text,'source title');assert.equal(v.list().find(x=>x.id===item.id).sourceUrl,'https://www.douyin.com/video/12345');}}
 finally{await v.close();await rm(dir,{recursive:true,force:true});}
 });

test('X/Twitter accepts post links and rejects home/profile links and lookalike hosts',()=>{
 for(const url of ['https://x.com/creator/status/1234567890','https://twitter.com/creator/status/1234567890?s=20','https://mobile.twitter.com/creator/status/1234567890/video/1','https://x.com/i/web/status/1234567890'])assert.equal(videoLink('分享 '+url),url);
 for(const url of ['https://x.com/','https://x.com/creator','https://x.com.evil.test/user/status/123','https://twitter.com@evil.test/user/status/123'])assert.throws(()=>videoLink(url));
});

 test('Mainstream platform links and subscription service boundaries',()=>{
 for(const url of ['https://v.qq.com/x/page/a123.html','https://www.iqiyi.com/v_123.html','https://v.youku.com/v_show/id_123.html','https://www.mgtv.com/b/1/123.html','https://www.ixigua.com/123456/','https://www.zhihu.com/zvideo/123456','https://www.tiktok.com/@user/video/123456'])assert.equal(videoLink(url),url);
 for(const url of ['https://v.qq.com.evil.test/x','https://iqiyi.com.evil.test/x','https://netflix.com/watch/123','https://www.disneyplus.com/play/123'])assert.throws(()=>videoLink(url));
 });

test('Cover dimensions and reference material are validated before queueing',async()=>{
 const dir=await mkdtemp(path.join(os.tmpdir(),'cover-test-'));const v=new VideoWorkbench(process.cwd(),{directory:dir,runner:async(item,folder)=>{await writeFile(path.join(folder,'result.json'),JSON.stringify({text:'cover',files:[]}));}});
 try{await v.ready;for(const width of [0,319,4097,1080.5])await assert.rejects(()=>v.create({kind:'cover',text:'test',width,height:720}),/尺寸|宽高/);await assert.rejects(()=>v.create({kind:'cover',text:'test',referenceId:'missing'}),/参考图/);const r=await v.create({kind:'cover',text:'test',width:1920,height:1080});assert.equal(r.item.spec.width,1920);assert.equal(r.item.spec.height,1080);await wait(()=>v.get(r.item.id).status==='completed');}finally{await v.close();await rm(dir,{recursive:true,force:true});}
});

test('Download automatically queues subtitles and preserves video when extraction fails',async()=>{
 const dir=await mkdtemp(path.join(os.tmpdir(),'video-auto-sub-'));const v=new VideoWorkbench(process.cwd(),{directory:dir,runner:async(item,folder)=>{if(item.kind==='subtitles')throw Error('subtitle fixture failure');await writeFile(path.join(folder,'media.mp4'),'video fixture');await writeFile(path.join(folder,'result.json'),JSON.stringify({text:'video',files:['media.mp4']}));}});
 try{await v.ready;const {item}=await v.create({kind:'download',url:'https://www.douyin.com/video/12345',autoSubtitles:true});await wait(()=>v.list().some(i=>i.sourceId===item.id&&i.status==='failed'));assert.equal(v.get(item.id).status,'completed');assert.deepEqual(v.get(item.id).files,['media.mp4']);assert.equal(v.list().filter(i=>i.sourceId===item.id).length,1);}finally{await v.close();await rm(dir,{recursive:true,force:true});}
});
