import assert from 'node:assert/strict';import {chromium}from'playwright-core';import{mkdir,writeFile}from'node:fs/promises';import{createApp}from'../src/server.mjs';
const app=await createApp({dbPath:':memory:'});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+app.server.address().port;const browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});const page=await browser.newPage({viewport:{width:1440,height:1050}}),errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));await mkdir('output/verification',{recursive:true});
try{await page.goto(base);await page.getByText('你的第一份洞察，正在等你开始').waitFor();await page.screenshot({path:'output/verification/desktop-empty.png',fullPage:true});checks.push('首次打开为空状态，没有伪装平台数据');await page.getByRole('button',{name:'体验演示数据 →'}).click();await page.getByText('演示模式 · 以下评论为人工编写',{exact:false}).waitFor();await page.locator('.bar-row').first().waitFor();assert.equal(await page.locator('.metric strong').first().textContent(),'40');await page.screenshot({path:'output/verification/desktop-demo.png',fullPage:true});checks.push('演示数据明确标记，40条记录和需求面板正常');const keywordDownload=page.waitForEvent('download');await page.getByRole('button',{name:'导出关键词'}).click();await(await keywordDownload).saveAs('output/verification/keywords-export.xlsx');checks.push('关键词统计表可真实导出');await page.locator('.bar-row').first().click();await page.locator('.filter-chip').waitFor();assert.ok(await page.locator('tbody tr').count()>0);await page.getByRole('button',{name:'清除关键词'}).click();await page.locator('.favorite').first().click();await page.locator('.favorite.on').first().waitFor();await page.locator('#favorite-filter').check();await page.waitForFunction(()=>document.querySelectorAll('tbody tr').length===1);assert.equal(await page.locator('tbody tr').count(),1);await page.locator('.comment-text').first().click();await page.locator('#detail-modal[open]').waitFor();await page.getByRole('button',{name:'关闭',exact:true}).last().click();checks.push('关键词筛选、收藏过滤、原文弹窗可操作');
await page.getByRole('button',{name:'新建分析',exact:false}).first().click();assert.equal(await page.locator('#task-modal .tabs button').count(),3);assert.equal(await page.getByRole('button',{name:'导入文件',exact:true}).count(),0);assert.equal(await page.locator('input[type=file]').count(),0);await page.getByRole('button',{name:'关闭',exact:true}).first().click();checks.push('新建任务仅保留链接、搜索、主页，导入入口已移除');
const fixture=app.store.create({name:'browser-test.csv',mode:'import'});const demoTask=app.store.list().find(t=>t.mode==='demo');const samples=app.store.comments(demoTask.id).slice(0,2);samples[0]={...samples[0],text:'<img src=x onerror=alert(1)>价格太贵'};app.store.insert(fixture.id,samples);app.store.update(fixture.id,{status:'completed'});await page.goto(base+'/?task='+fixture.id);await page.waitForFunction(()=>document.querySelectorAll('tbody tr').length===2);assert.equal(await page.locator('tbody img').count(),0);assert.equal(await page.getByRole('button',{name:'追加数据',exact:true}).count(),0);checks.push('历史导入任务仍可查看且安全转义，不再提供追加入口');
const download=page.waitForEvent('download');await page.getByRole('button',{name:'↓ 导出'}).click();const d=await download;await d.saveAs('output/verification/browser-export.xlsx');assert.equal(await d.failure(),null);checks.push('Excel文件真实下载');
const selectedId=new URL(page.url()).searchParams.get('task');assert.ok(selectedId);await page.reload();await page.getByText('browser-test.csv',{exact:true}).first().waitFor();assert.equal(await page.locator('.keyword-current').getAttribute('data-task-id'),selectedId);await page.locator('#scope-details summary').click();await page.locator('#noise-filter').check();assert.equal(await page.locator('#scope-details').evaluate(el=>el.open),true);await page.locator('#export-type').selectOption('csv');await page.locator('.favorite').first().click();await page.locator('.favorite.on').first().waitFor();assert.equal(await page.locator('#export-type').inputValue(),'csv');checks.push('刷新保留新任务、筛选保持范围面板展开、收藏后保持导出格式');

for(const [name,width,height]of[['tablet',820,1180],['mobile',390,844]]){await page.setViewportSize({width,height});await page.screenshot({path:`output/verification/${name}-result.png`,fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.getByRole('button',{name:'新建分析',exact:false}).first().click();assert.ok(await page.locator('#task-modal').evaluate(el=>el.getBoundingClientRect().width<=innerWidth));await page.getByRole('button',{name:'关闭',exact:true}).first().click();checks.push(name+' 无页面横向溢出，弹窗可用');}
await page.locator('[data-nav="tasks"]').first().click();await page.locator('.task-card').first().waitFor();await page.locator('[data-nav="connections"]').first().click();await page.locator('.connection-card').first().waitFor();checks.push('任务列表与平台连接入口可切换');assert.deepEqual(errors,[]);await writeFile('output/verification/browser-check.json',JSON.stringify({ok:true,checks,errors},null,2));console.log(JSON.stringify({ok:true,checks},null,2));}finally{await browser.close();await app.close();}
