import {translateText} from './lib/translation.mjs';
import {searchSuggestions} from './lib/search-suggestions.mjs';
import {fetchSkill} from './lib/cover-skill.mjs';
import {VideoWorkbench} from './lib/video-workbench.mjs';
import {AutoReply} from './lib/auto-reply.mjs';
import {sendBrowserReply} from './lib/reply-browser.mjs';
import {wordcloudSVG} from './lib/wordcloud.mjs';
import http from 'node:http';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { randomUUID } from 'node:crypto';
import ExcelJS from 'exceljs';
import { Store } from './lib/store.mjs';
import { CollectionManager } from './lib/collection-manager.mjs';
import {PLATFORM_INFO} from './public/platforms.js';
import { analyze,eligible,classify,sentiment,tokens,sourceUrl,words } from './lib/core.mjs';
import { readRows,mapRows,csv,aliases } from './lib/import.mjs';
import { Feishu } from './lib/feishu.mjs';
import { demoRows } from './lib/demo.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const columns=[['platform','平台'],['text','评论内容'],['likes','点赞数'],['created_at','评论时间'],['title','作品标题'],['source_url','来源链接'],['post_id','作品ID'],['comment_id','评论ID'],['parent_id','父评论ID'],['category','需求分类'],['sentiment','情绪参考'],['identity','去重依据'],['author','作者昵称'],['parent_text','上级评论正文']];
export async function createApp({dbPath=process.env.DATA_PATH||path.join(root,'.runtime','comments.sqlite'),collectorFactory,replySender,feishuOptions={},feishuConfigPath=path.join(root,'.runtime','feishu.json')}={}) {
const store=new Store(dbPath),collector=collectorFactory?collectorFactory(store):new CollectionManager(store,root),stages=new Map();
const videos=new VideoWorkbench(root,{browser:collector.browser,cookiesFor:async p=>collector.browser?.context?await(await collector.browser.context(p)).cookies():[],directory:dbPath===':memory:'?path.join(root,'.runtime','video-test-'+randomUUID()):path.join(root,'.runtime/video-workbench')});
const feishu=new Feishu(store,feishuConfigPath,feishuOptions);
const replies=new AutoReply(store,replySender||((c,g,allowed)=>sendBrowserReply(collector.browser,c,g,allowed)));
const cleanup=setInterval(()=>{for(const [k,v] of stages)if(Date.now()-v.time>15*60e3)stages.delete(k);},60000);cleanup.unref();
const json=(res,data,status=200)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data));};
async function body(req){let bytes=0,chunks=[];for await(const chunk of req){bytes+=chunk.length;if(bytes>16*1024*1024)throw new Error('上传内容过大，单文件请控制在 10 MB 内');chunks.push(chunk);}try{return JSON.parse(Buffer.concat(chunks).toString('utf8')||'{}');}catch{throw new Error('请求格式不正确');}}
function options(input={}) {const opts={watch:words(input.watch).join(','),exclude:words(input.exclude).join(','),since:input.since||'',until:input.until||'',maxPosts:Math.max(1,Math.min(30,Math.floor(Number(input.maxPosts))||10)),maxComments:input.maxComments==null||input.maxComments===''||input.maxComments==='all'?null:Math.max(10,Math.min(1000,Math.floor(Number(input.maxComments))||100))};for(const k of ['since','until'])if(opts[k]&&(!/^\d{4}-\d{2}-\d{2}$/.test(opts[k])||!Number.isFinite(Date.parse(opts[k]))||new Date(opts[k]).toISOString().slice(0,10)!==opts[k]))throw new Error('日期格式不正确');if(opts.since&&opts.until&&opts.since>opts.until)throw new Error('开始日期不能晚于结束日期');return opts;}
function select(task,url){const opts={...task.options,platform:url.searchParams.get('platform')||'',includeNoise:url.searchParams.get('noise')==='1'};const all=store.comments(task.id);const parents=new Map(all.filter(c=>c.comment_id).map(c=>[c.platform+':'+c.post_id+':'+c.comment_id,c.text]));const analysis=analyze(all,opts);const q=(url.searchParams.get('q')||'').toLowerCase(),word=(url.searchParams.get('word')||'').toLowerCase(),category=url.searchParams.get('category')||'',favorite=url.searchParams.get('favorite')==='1';const kw=analysis.keywords.find(k=>k.word===word);const ids=kw?new Set(kw.ids):null;const scope=url.searchParams.get('scope');const matched=all.filter(c=>(scope==='all'?(!opts.platform||c.platform===opts.platform):eligible(c,opts))&&(scope!=='posts'||!!c.post_id)&&(scope!=='needs'||classify(c.text).length>0)&&(!q||c.text.toLowerCase().includes(q))&&(!word||(ids?ids.has(c.key):c.text.toLowerCase().includes(word)))&&(!category||classify(c.text).includes(category))&&(!favorite||c.favorite));return {all,analysis,matched:matched.map(c=>({...c,category:classify(c.text).join('、'),sentiment:sentiment(c.text),parent_text:c.parent_id?(parents.get(c.platform+':'+c.post_id+':'+c.parent_id)||''):''}))};}
const server=http.createServer(async(req,res)=>{try{
 const host=req.headers.host||'';if(!/^(127\.0\.0\.1|localhost)(:\d+)?$/.test(host)){json(res,{error:'仅允许本机访问'},403);return;}
 res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('X-Frame-Options','DENY');
 const url=new URL(req.url,'http://'+host),route=url.pathname;
 if(!['GET','HEAD'].includes(req.method)){if(req.headers.origin&&req.headers.origin!==url.origin){json(res,{error:'拒绝跨站请求'},403);return;}if(route!=='/api/video/upload'&&!String(req.headers['content-type']).startsWith('application/json')){json(res,{error:'需要 JSON 请求'},415);return;}}
 if(route==='/api/health'&&req.method==='GET'){json(res,{app:'kk-tingjian',instance:process.env.KK_DESKTOP_INSTANCE||null});return;}
 if(route==='/api/translate'&&req.method==='POST'){json(res,await translateText(await body(req)));return;}
 if(route==='/api/video/cover-skill'&&req.method==='POST'){const input=await body(req);json(res,await fetchSkill(input.url));return;}
 if(route==='/api/video/state'&&req.method==='GET'){json(res,await videos.status());return;}
 if(route==='/api/video/upload'&&req.method==='POST'){json(res,await videos.upload(req,url.searchParams.get('filename'),url.searchParams.get('role')));return;}
 if(route==='/api/video/jobs'&&req.method==='POST'){json(res,await videos.create(await body(req)));return;}
 const videoRoute=route.match(/^\/api\/video\/([a-f0-9-]{36})\/(cancel|retry|archive|file)$/);if(videoRoute){if(videoRoute[2]==='file'&&req.method==='GET'){await videos.file(videoRoute[1],url.searchParams.get('name'),res,req);return;}if(req.method==='POST'){json(res,await videos.action(videoRoute[1],videoRoute[2]));return;}}
 if(route==='/api/reply-settings'&&req.method==='GET'){json(res,replies.status());return;}
 if(route==='/api/reply-settings'&&req.method==='POST'){json(res,replies.save(await body(req)));return;}
 if(route==='/api/reply-stop'&&req.method==='POST'){replies.pause();json(res,replies.status());return;}
 if(route==='/api/feishu'&&req.method==='GET'){json(res,await feishu.status());return;}
 if(route==='/api/feishu'&&req.method==='POST'){json(res,await feishu.save(await body(req)));return;}
 if(route==='/api/state'&&req.method==='GET'){json(res,{tasks:store.list(),connections:collector.connectionState,active:collector.active,activeTaskIds:collector.activeTaskIds||[collector.active].filter(Boolean),maxConcurrent:collector.maxConcurrent||1,engines:{mediacrawler:collector.engineStatus||{ready:false}}});return;}
 if(route==='/api/search-suggestions'&&req.method==='GET'){json(res,await searchSuggestions(collector.browser,url.searchParams.get('q')));return;}
 if(route==='/api/connect'&&req.method==='POST'){const b=await body(req);json(res,await collector.connect(b.platform));return;}
 if(route==='/api/import/preview'&&req.method==='POST'){const b=await body(req);if(typeof b.data!=='string'||typeof b.filename!=='string')throw new Error('请选择文件');const data=Buffer.from(b.data,'base64');if(data.length>10*1024*1024)throw new Error('文件超过 10 MB，请拆分导入');const parsed=await readRows(data,b.filename);if(stages.size>=10)throw new Error('待导入文件过多，请完成当前导入或稍后重试');const token=randomUUID();stages.set(token,{...parsed,time:Date.now(),filename:b.filename});json(res,{token,headers:parsed.headers,mapping:parsed.mapping,preview:parsed.rows.slice(0,5),count:parsed.rows.length,fields:Object.keys(aliases)});return;}
 if(route==='/api/import/commit'&&req.method==='POST'){const b=await body(req),stage=stages.get(b.token);if(!stage||Date.now()-stage.time>15*60e3)throw new Error('预览已过期，请重新选择文件');if(stage.result){json(res,stage.result);return;}const mapping=b.mapping||stage.mapping;for(const h of Object.values(mapping))if(h&&!stage.headers.includes(h))throw new Error('字段映射与文件不一致');const rows=mapRows(stage.rows,mapping,{platform:b.platform});if(!rows.length)throw new Error('没有有效的评论正文，请检查字段映射');let task=b.taskId?store.get(b.taskId):null;if(b.taskId&&(!task||task.mode!=='import'))throw new Error('仅可向导入任务追加数据');task ||= store.create({name:String(b.name||stage.filename).slice(0,100),mode:'import',options:options(b.options)});const result=store.insert(task.id,rows);store.update(task.id,{status:'completed',message:`导入 ${rows.length} 条有效记录，新增 ${result.added} 条，重复 ${result.duplicates} 条，空正文 ${stage.rows.length-rows.length} 条。`});stage.result={task:store.get(task.id),...result};json(res,stage.result);return;}
 if(route==='/api/tasks'&&req.method==='POST'){const b=await body(req);if(!['links','search','creator'].includes(b.mode))throw new Error('选择链接采集或关键词搜索');collector.assertAvailable?.();const opts=options(b.options);opts.engine=b.engine||'browser';opts.includeReplies=b.options?.includeReplies!==false;if(!['browser','mediacrawler'].includes(opts.engine))throw new Error('采集方式不支持');if(opts.engine==='mediacrawler'&&!collector.engineStatus?.ready)throw new Error('MediaCrawler 尚未安装或未通过运行检查');if(b.mode==='creator'&&opts.engine!=='mediacrawler')throw new Error('创作者主页采集需要选择增强采集');if(b.mode==='links'||b.mode==='creator'){const input=String(b.input||'');const links=input.match(/https?:\/\/[^\s<>"，。]+/g)||[];if(!links.length)throw new Error('请粘贴作品分享链接');opts.links=[...new Set(links)].map(sourceUrl);if(opts.links.length>30)throw new Error('每次最多 30 个作品');opts.maxPosts=Math.max(opts.maxPosts,opts.links.length);}else{opts.query=String(b.input||'').trim().slice(0,100);if(!opts.query)throw new Error('请输入搜索关键词');opts.platforms=[...new Set((b.platforms||[]).filter(p=>PLATFORM_INFO.some(x=>x.id===p)))];if(!opts.platforms.length)throw new Error('至少选择一个平台');}if(opts.engine==='browser'&&[...(opts.platforms||[]),...(opts.links||[]).map(l=>l.platform)].some(p=>!['douyin','xiaohongshu'].includes(p)))throw new Error('该平台请使用 MediaCrawler 增强采集');const task=store.create({name:String(b.name||b.input||'评论采集').slice(0,100),mode:b.mode,options:opts});await collector.run(task.id);json(res,{task:store.get(task.id)});return;}
 if(route==='/api/demo'&&req.method==='POST'){let task=store.list().find(t=>t.mode==='demo');if(!task){task=store.create({name:'AI 视频创作 · 演示分析',mode:'demo',options:{watch:'价格,新手,字幕'}});store.insert(task.id,demoRows());store.update(task.id,{status:'completed',message:'演示数据为人工编写，仅用于体验功能，不代表平台真实评论。'});}json(res,{task:store.get(task.id)});return;}
 if(route==='/api/template.csv'){const sample=[{platform:'抖音',text:'请替换成真实评论内容',source_url:'',comment_id:'',post_id:'',created_at:'2026-10-04T10:00:00+08:00',likes:0}];res.writeHead(200,{'Content-Type':'text/csv; charset=utf-8','Content-Disposition':'attachment; filename="comments-template.csv"'});res.end(csv(sample,columns.slice(0,9)));return;}
 const match=route.match(/^\/api\/tasks\/([\w-]+)(?:\/(resume|continue|pause|favorite|export|feishu))?$/);
 if(match){const task=store.get(match[1]);if(!task){json(res,{error:'任务不存在'},404);return;}const action=match[2];
 if(action==='continue'&&req.method==='POST'){await collector.run(task.id,{continueAnalysis:true});json(res,{task:store.get(task.id)});return;}
 if(action==='resume'&&req.method==='POST'){await collector.run(task.id);json(res,{task:store.get(task.id)});return;}
 if(action==='pause'&&req.method==='POST'){if(!['links','search','creator'].includes(task.mode))throw new Error('此任务无需暂停');collector.pause(task.id);json(res,{task:store.get(task.id)});return;}
 if(action==='favorite'&&req.method==='POST'){const b=await body(req);store.favorite(task.id,b.key,!!b.on);json(res,{ok:true});return;}
 if(action==='feishu'&&req.method==='POST'){json(res,await feishu.export(task,select(task,url).matched));return;}
 if(action==='export'&&req.method==='GET'){const result=select(task,url),kind=url.searchParams.get('kind'),rows=kind==='keywords'?analyze(result.matched,{...task.options,includeNoise:url.searchParams.get('noise')==='1'}).keywords:result.matched;if(kind==='wordcloud'){res.setHeader('Content-Type','image/svg+xml; charset=utf-8');res.setHeader('Content-Disposition','attachment; filename="comment-wordcloud.svg"');res.end(wordcloudSVG(analyze(result.matched,{...task.options,includeNoise:true}).keywords,task.name));return;}if(url.searchParams.get('format')==='json'){res.setHeader('Content-Disposition','attachment; filename="comments.json"');json(res,{task:task.name,scope:'仅当前已获取且符合筛选的样本',comments:rows});return;}const cols=kind==='keywords'?[['word','关键词'],['comments','评论数'],['posts','作品数'],['occurrences','出现次数'],['share','评论占比']]:columns;const format=url.searchParams.get('format')==='xlsx'?'xlsx':'csv';res.setHeader('Content-Disposition',`attachment; filename="${task.mode==='demo'?'DEMO-':''}comments-${task.id.slice(0,8)}.${format}"`);if(format==='csv'){res.setHeader('Content-Type','text/csv; charset=utf-8');res.end(csv(rows,cols));}else{const wb=new ExcelJS.Workbook();const ws=wb.addWorksheet(kind==='keywords'?'关键词':'评论');ws.columns=cols.map(([key,header])=>({key,header,width:key==='text'?60:22}));ws.addRows(rows.map(r=>Object.fromEntries(cols.map(([k])=>[k,r[k]??'']))));ws.getRow(1).font={bold:true};ws.views=[{state:'frozen',ySplit:1}];const meta=wb.addWorksheet('范围说明');meta.addRows([['任务',task.name],['数据类型',task.mode==='demo'?'演示数据（人工编写）':'已获取样本'],['采集范围','仅当前可获取样本，不代表平台全部评论'],['分析方式',result.analysis.engine],['原始评论数',result.all.length],['本次导出评论数',result.matched.length],['筛选条件',JSON.stringify(Object.fromEntries([...url.searchParams].filter(([k])=>!['format','kind','page'].includes(k))))],['导出时间',new Date().toISOString()]]);res.setHeader('Content-Type','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');res.end(Buffer.from(await wb.xlsx.writeBuffer()));}return;}
 if(!action&&req.method==='GET'){const result=select(task,url);const pageSize=10;const page=Math.min(Math.max(1,Math.ceil(result.matched.length/pageSize)),Math.max(1,Math.floor(Number(url.searchParams.get('page')))||1));json(res,{task,sources:store.sources(task.id),analysis:{...result.analysis,keywords:result.analysis.keywords.map(({ids,...k})=>k),topics:result.analysis.topics.map(({ids,...t})=>t)},hotComments:[...result.all].sort((a,b)=>b.likes-a.likes||a.key.localeCompare(b.key)).slice(0,5).map(c=>({...c,category:classify(c.text).join('、'),sentiment:sentiment(c.text)})),comments:result.matched.slice((page-1)*pageSize,page*pageSize),matched:result.matched.length,page,pages:Math.max(1,Math.ceil(result.matched.length/pageSize))});return;}}
 if(route.startsWith('/api/')){json(res,{error:'接口不存在'},404);return;}
 if(req.method!=='GET'&&req.method!=='HEAD'){res.writeHead(405);res.end();return;}
 const files={'/':'index.html','/languages.js':'languages.js','/translation-ui.js':'translation-ui.js','/app.js':'app.js','/video-ui.js':'video-ui.js','/feishu-ui.js':'feishu-ui.js','/platforms.js':'platforms.js','/mediacrawler-license.txt':'mediacrawler-license.txt','/styles.css':'styles.css'};if(!files[route]){res.writeHead(404);res.end('Not found');return;}const file=files[route];res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'");res.setHeader('Content-Type',file.endsWith('.css')?'text/css':file.endsWith('.js')?'text/javascript':file.endsWith('.txt')?'text/plain; charset=utf-8':'text/html; charset=utf-8');res.setHeader('Cache-Control','no-cache');res.end(await readFile(path.join(root,'src/public',file)));
 }catch(e){if(!res.headersSent)json(res,{error:e.message},400);else res.end();}});
return {server,store,collector,replies,close:async()=>{clearInterval(cleanup);await replies.close();await videos.close();await collector.close();await new Promise(r=>server.close(r));store.close();}};
}
if(process.argv[1]===fileURLToPath(import.meta.url)){const app=await createApp();const port=Number(process.env.PORT||5188);app.server.listen(port,'127.0.0.1',()=>console.log(`评论洞察工作台 http://127.0.0.1:${port}`));app.server.on('error',e=>{console.error(e.message);process.exitCode=1;});for(const signal of ['SIGINT','SIGTERM'])process.on(signal,()=>app.close().then(()=>process.exit(0)));}
